name: build-artifacts (disabled in favor of semantic-release)

# NOTE: artifacts are now attached by python-semantic-release in the publish job.
# This workflow is retained for reference but disabled.

on: { workflow_dispatch: {} }

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Artifacts are handled by semantic-release.'
