name: CI

on:
  push:
    branches: [ develop, feat/**, fix/**, docs/**, chore/**, refactor/**, test/**, ci/** ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv and deps
        run: |
          pip install uv
          uv pip install --system -e .[dev]
      - name: Ruff format (check)
        run: ruff format --check .
      - name: Ruff lint
        run: ruff check .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv and deps
        run: |
          pip install uv
          uv pip install --system -e .[dev]
      - name: Pyright
        run: pyright

  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv and deps
        run: |
          pip install uv
          uv pip install --system -e .[dev]
      - name: Pytest
        run: pytest -q
