name: promotion-guard

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review, labeled, unlabeled]

permissions:
  pull-requests: write
  contents: read

jobs:
  guard:
    if: github.base_ref == 'main' && github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Require 'promote' label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = (context.payload.pull_request.labels || []).map(l => l.name);
            if (!labels.includes('promote')) {
              core.setFailed('Add the ' + 'promote' + ' label to confirm develop -> main promotion. Use Merge commit, not Squash.');
            }
      - name: Comment guidance (merge method)
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const number = context.payload.pull_request.number;
            const body = 'Promotion PR detected (develop -> main)

- Use **Merge commit**, not Squash.';
            await github.rest.issues.createComment({ owner, repo, issue_number: number, body });
