name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: mcp-devhatchery
          target-branch: main
          include-v-in-tag: true
          changelog-types: |
            [{
              "type": "feat",
              "section": "Features"
            },{
              "type": "fix",
              "section": "Bug Fixes"
            },{
              "type": "docs",
              "section": "Documentation"
            },{
              "type": "chore",
              "section": "Chores"
            }]
